# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            JPBerriz
tagline:          'JPBerriz'
description:      'Life is Art'
url:              https://jpberriz.com
baseurl:          /
theme:            Hyde

author:           
  name:           'Juan Pablo Berrizbeitia'
  url:            'http://jpberriz.com'

paginate:         5
paginate_path:    /notes/page:num/


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jpberriz/jpberriz.com

include:          ['_pages']

# Site search 
tipue_search:
  include:
    pages:        true

# Google Analytics
google_analytics: G-P8VDRWRQ8P